#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst xfce4-power-manager

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

# set screen layout (CUSTOMIZE FOR YOUR SETUP)
# xrandr --output eDP1 --mode 1920x1200 --pos 0x1920 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output DP3-1 --mode 1920x1080 --pos 1698x0 --rotate right --output DP3-2 --off --output DP3-2-1 --mode 1920x1080 --pos 2778x1129 --rotate normal --output DP3-2-2 --off --output VIRTUAL1 --off

## Reload theme
archcraft-reload-theme

## Launch Polybar or Tint2
bash ~/.config/openbox/themes/launch-bar.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
exec plank &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu (DISABLED - conflicts with Super+arrow keys)
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## User Friendly Network Menu
#nm-applet --indicator &

## User Friendly Bluetooth Menu
#blueman-applet &

# Custom redshift script (CUSTOMIZE PATH)
# bash ~/Support/scripts/redshift-red.sh
