# Archcraft ZSH Configuration
# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="archcraft"

# Disable automatic updates
zstyle ':omz:update' mode disabled

# Which plugins would you like to load?
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# On-demand rehash for pacman
zshcache_time="$(date +%s%N)"

autoload -Uz add-zsh-hook

rehash_precmd() {
  if [[ -a /var/cache/zsh/pacman ]]; then
    local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
    if (( zshcache_time < paccache_time )); then
      rehash
      zshcache_time="$paccache_time"
    fi
  fi
}

add-zsh-hook -Uz precmd rehash_precmd

# Aliases
alias zshconfig="geany ~/.zshrc"
alias ohmyzsh="thunar ~/.oh-my-zsh"

# ls aliases
alias l='ls -lh'
alias ll='ls -lah'
alias la='ls -A'
alias lm='ls -m'
alias lr='ls -R'
alias lg='ls -l --group-directories-first'

# git aliases
alias gcl='git clone --depth 1'
alias gi='git init'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin master'

# Environment Variables
export PATH="$HOME/.asdf/shims:$PATH"
export PATH="$PATH:/home/trevor/.dotnet/tools"
export NVIDIA_VISIBLE_DEVICES=all
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$HOME/.dotnet:$PATH:$HOME/.dotnet/tools
export BROWSER=google-chrome
